/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.ImageIcon;
import javax.swing.JEditorPane;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 * The class responsible for displaying the menu options, and to launch the game.
 * Create and run an instance of this Object in HangmanGame.java to launch the
 * application.
 * @author CE170028 Truong Duy Minh, CE171454 Hua Tien Thanh
 */
public class MainMenu extends javax.swing.JFrame 
        implements WindowListener{

    private final Font OPTION_PANE_FONT = new Font("Segoe UI", Font.BOLD, 24);
    
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        this.addWindowListener(this);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/hangman_128.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgHowToPlay = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        lblHowToPlay = new javax.swing.JLabel();
        btnClose_dlgHowToPlay = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtHowToPlay = new javax.swing.JEditorPane();
        dlgAboutUs = new javax.swing.JDialog();
        pnlAboutUs = new javax.swing.JPanel();
        lblAboutUs = new javax.swing.JLabel();
        btnClose_dlgAboutUs = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ImageIcon fptLogo = new ImageIcon("src/images/2021-FPTU-Eng_143x72.png");
        lblLogo = new javax.swing.JLabel(fptLogo);
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMemberName = new javax.swing.JEditorPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtMemberRollNo = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        btnStartGame = new javax.swing.JButton();
        btnHowToPlay = new javax.swing.JButton();
        btnAboutUs = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();

        dlgHowToPlay.setTitle("How To Play");
        dlgHowToPlay.setModal(true);
        dlgHowToPlay.setUndecorated(true);
        dlgHowToPlay.setResizable(false);
        dlgHowToPlay.setSize(new java.awt.Dimension(650, 450));

        jPanel1.setBackground(new java.awt.Color(239, 247, 226));

        lblHowToPlay.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblHowToPlay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHowToPlay.setText("How To Play");
        lblHowToPlay.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnClose_dlgHowToPlay.setBackground(new java.awt.Color(0, 153, 153));
        btnClose_dlgHowToPlay.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnClose_dlgHowToPlay.setForeground(new java.awt.Color(0, 102, 102));
        btnClose_dlgHowToPlay.setText("Close");
        btnClose_dlgHowToPlay.setContentAreaFilled(false);
        btnClose_dlgHowToPlay.setFocusPainted(false);
        btnClose_dlgHowToPlay.setRequestFocusEnabled(false);
        btnClose_dlgHowToPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClose_dlgHowToPlayActionPerformed(evt);
            }
        });

        txtHowToPlay.setContentType("text/html"); // NOI18N
        txtHowToPlay.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jScrollPane4.setViewportView(txtHowToPlay);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose_dlgHowToPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4)
                    .addComponent(lblHowToPlay, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHowToPlay)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnClose_dlgHowToPlay)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout dlgHowToPlayLayout = new javax.swing.GroupLayout(dlgHowToPlay.getContentPane());
        dlgHowToPlay.getContentPane().setLayout(dlgHowToPlayLayout);
        dlgHowToPlayLayout.setHorizontalGroup(
            dlgHowToPlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dlgHowToPlayLayout.setVerticalGroup(
            dlgHowToPlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dlgAboutUs.setTitle("About Us");
        dlgAboutUs.setModal(true);
        dlgAboutUs.setUndecorated(true);
        dlgAboutUs.setResizable(false);
        dlgAboutUs.setSize(new java.awt.Dimension(750, 593));

        pnlAboutUs.setBackground(new java.awt.Color(253, 235, 252));

        lblAboutUs.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblAboutUs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAboutUs.setText("About Us");
        lblAboutUs.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnClose_dlgAboutUs.setBackground(new java.awt.Color(153, 0, 0));
        btnClose_dlgAboutUs.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnClose_dlgAboutUs.setForeground(new java.awt.Color(153, 0, 0));
        btnClose_dlgAboutUs.setText("Close");
        btnClose_dlgAboutUs.setContentAreaFilled(false);
        btnClose_dlgAboutUs.setFocusPainted(false);
        btnClose_dlgAboutUs.setRequestFocusEnabled(false);
        btnClose_dlgAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClose_dlgAboutUsActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("<html> This project was made by group 3, class SE1704, FPT University.<br> Semester: SP23<br> Subject: CSD201 (Data Structures and Algorithms)<br> Mentor: Vo Hong Khanh </html>");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Member Name");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Roll No.");

        lblLogo.setText("FPT Logo here");

        txtMemberName.setContentType("text/html"); // NOI18N
        txtMemberName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtMemberName.setFocusable(false);
        jScrollPane1.setViewportView(txtMemberName);

        txtMemberRollNo.setContentType("text/html"); // NOI18N
        txtMemberRollNo.setFocusable(false);
        jScrollPane5.setViewportView(txtMemberRollNo);

        javax.swing.GroupLayout pnlAboutUsLayout = new javax.swing.GroupLayout(pnlAboutUs);
        pnlAboutUs.setLayout(pnlAboutUsLayout);
        pnlAboutUsLayout.setHorizontalGroup(
            pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAboutUsLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAboutUs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAboutUsLayout.createSequentialGroup()
                        .addGroup(pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlAboutUsLayout.createSequentialGroup()
                                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnClose_dlgAboutUs, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(30, 30, 30)
                        .addGroup(pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(jScrollPane5))))
                .addGap(36, 36, 36))
        );
        pnlAboutUsLayout.setVerticalGroup(
            pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAboutUsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblAboutUs)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose_dlgAboutUs))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout dlgAboutUsLayout = new javax.swing.GroupLayout(dlgAboutUs.getContentPane());
        dlgAboutUs.getContentPane().setLayout(dlgAboutUsLayout);
        dlgAboutUsLayout.setHorizontalGroup(
            dlgAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAboutUs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dlgAboutUsLayout.setVerticalGroup(
            dlgAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAboutUs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hangman v1.1.1");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setText("HANGMAN PLUS");

        btnStartGame.setBackground(new java.awt.Color(223, 249, 243));
        btnStartGame.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnStartGame.setText("Start Game");
        btnStartGame.setFocusPainted(false);
        btnStartGame.setFocusable(false);
        btnStartGame.setPreferredSize(new java.awt.Dimension(329, 42));
        btnStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartGameActionPerformed(evt);
            }
        });

        btnHowToPlay.setBackground(new java.awt.Color(228, 255, 228));
        btnHowToPlay.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnHowToPlay.setText("How to Play");
        btnHowToPlay.setFocusPainted(false);
        btnHowToPlay.setFocusable(false);
        btnHowToPlay.setPreferredSize(new java.awt.Dimension(329, 42));
        btnHowToPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHowToPlayActionPerformed(evt);
            }
        });

        btnAboutUs.setBackground(new java.awt.Color(255, 234, 255));
        btnAboutUs.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnAboutUs.setText("About Us");
        btnAboutUs.setFocusPainted(false);
        btnAboutUs.setFocusable(false);
        btnAboutUs.setPreferredSize(new java.awt.Dimension(329, 42));
        btnAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutUsActionPerformed(evt);
            }
        });

        btnQuit.setBackground(new java.awt.Color(255, 204, 204));
        btnQuit.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnQuit.setText("Quit");
        btnQuit.setFocusPainted(false);
        btnQuit.setFocusable(false);
        btnQuit.setPreferredSize(new java.awt.Dimension(329, 42));
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnStartGame, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHowToPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAboutUs, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnStartGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHowToPlay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAboutUs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartGameActionPerformed
        // TODO add your handling code here:
        MainGameFrame game = new MainGameFrame();
        game.setLocationRelativeTo(null);
        game.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStartGameActionPerformed

    private void btnHowToPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHowToPlayActionPerformed
        // TODO add your handling code here:
        String gameRules = 
        "  <html>\n" +
        "    <style>\n" +
        "      html {\n" +
        "        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n" +
        "        font-size: 24;\n" +
        "      }\n" +
        "      p {\n" + 
        "        text-align: justify;\n" + 
        "      }\n" +
        "      ol {\n" +
        "        text-align: justify;\n" +
        "      }\n" +
        "      li {\n" +
        "        margin: 4px\n" +
        "      }\n" +
        "    </style>\n" +
        "    <p>Welcome! If you have never played Hangman, or if you need a reminder, here are the rules of the game:</p>\n" +
        "    <ol>\n" +
        "      <li>Choose your difficulty: There are 4 options for you, choose wisely! Especially that last one...</li>\n" +
        "      <li>You will start from level 1. There will be a \"hidden word\" containing only underscores which must be fully revealed.</li>\n" +
        "      <li>To reveal the entire word, you must choose the letters that make up the hidden word.</li>\n" +
        "      <li>If you choose a correct letter, that letter will be revealed on the hidden word and your score will be increased.</li>\n" +
        "      <li>Choose a wrong option, and the Hangman painting will have one extra stroke drawn. The game ends when the painting is completed.</li>\n" +
        "      <li>For the \"Easy\", \"Normal\", \"Hard\" difficulty, all completed words will not be repeated." +
        "          That means once you've completed all words of that difficulty, you will have completed that game.</li>\n" +
        "      <li>For the \"Asian\" difficulty, there is no final level. All completed words will be repeated, your job is to complete as many word as possible and get the highest score.</li>\n" +
        "    </ol>\n" +
        "    <p>Good luck!</p>\n" +
        "  </html>";
        Font editorPaneFont = new Font("Segoe UI", Font.PLAIN, 24);
        txtHowToPlay.putClientProperty(JEditorPane.HONOR_DISPLAY_PROPERTIES, Boolean.TRUE);
        txtHowToPlay.setFont(editorPaneFont);
        txtHowToPlay.setText(gameRules);
        txtHowToPlay.setCaretPosition(0); // auto scrolls to the top
        dlgHowToPlay.setLocationRelativeTo(null);
        dlgHowToPlay.setVisible(true);
    }//GEN-LAST:event_btnHowToPlayActionPerformed

    private void btnClose_dlgHowToPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClose_dlgHowToPlayActionPerformed
        // TODO add your handling code here:
        dlgHowToPlay.setVisible(false);
    }//GEN-LAST:event_btnClose_dlgHowToPlayActionPerformed

    private void btnClose_dlgAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClose_dlgAboutUsActionPerformed
        // TODO add your handling code here:
        dlgAboutUs.setVisible(false);
    }//GEN-LAST:event_btnClose_dlgAboutUsActionPerformed

    private void btnAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutUsActionPerformed
        // TODO add your handling code here:
        String memberNames =
        "  <html>\n" +
        "    <style>\n" +
        "      html {\n" +
        "        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n" +
        "        font-size: 24;\n" +
        "      }\n" +
        "      ol {\n" +
        "        text-align: justify;\n" +
        "        margin: 0px 25px\n" +
        "      }\n" +
        "      li {\n" +
        "        margin: 0px\n" +
        "      }\n" +
        "    </style>\n" +
        "    <body>\n" + 
        "      <ol>\n" +
        "      <li>Truong Duy Minh (Leader)</li>\n" +
        "      <li>Nguyen Huu Duy</li>\n" +
        "      <li>Hua Tien Thanh</li>\n" +
        "      <li>Phan Khanh Linh</li>\n" +
        "      <li>Vo Phuoc Tho</li>\n" +
        "      <li>Le Tan Quoc</li>\n" +
        "      </ol>\n" +
        "    </body>\n" +
        "  </html>";
        String memberRollNo =
        "  <html>\n" +
        "    <style>\n" +
        "      html {\n" +
        "        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n" +
        "        font-size: 24;\n" +
        "      }\n" +
        "      ul {\n" +
        "        text-align: justify;\n" +
        "        margin: 0px 0px\n" +
        "      }\n" +
        "      li {\n" +
        "        margin: 0px\n" +
        "      }\n" +
        "    </style>\n" +
        "    <body>\n" + 
        "      <ul>\n" +
        "      <li>CE170029</li>\n" +
        "      <li>CE170563</li>\n" +
        "      <li>CE171454</li>\n" +
        "      <li>CE171528</li>\n" +
        "      <li>CE161117</li>\n" +
        "      <li>CE161868</li>\n" +
        "      </ol>\n" +
        "    </body>\n" +
        "  </html>";
        Font editorPaneFont = new Font("Segoe UI", Font.PLAIN, 24);
        txtMemberName.putClientProperty(JEditorPane.HONOR_DISPLAY_PROPERTIES, Boolean.TRUE);
        txtMemberRollNo.putClientProperty(JEditorPane.HONOR_DISPLAY_PROPERTIES, Boolean.TRUE);
        txtMemberName.setFont(editorPaneFont);
        txtMemberRollNo.setFont(editorPaneFont);
        txtMemberName.setText(memberNames);
        txtMemberRollNo.setText(memberRollNo);
        dlgAboutUs.setLocationRelativeTo(null);
        dlgAboutUs.setVisible(true);
    }//GEN-LAST:event_btnAboutUsActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        // TODO add your handling code here:
        this.windowClosing(null);
    }//GEN-LAST:event_btnQuitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAboutUs;
    private javax.swing.JButton btnClose_dlgAboutUs;
    private javax.swing.JButton btnClose_dlgHowToPlay;
    private javax.swing.JButton btnHowToPlay;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnStartGame;
    private javax.swing.JDialog dlgAboutUs;
    private javax.swing.JDialog dlgHowToPlay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblAboutUs;
    private javax.swing.JLabel lblHowToPlay;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel pnlAboutUs;
    private javax.swing.JEditorPane txtHowToPlay;
    private javax.swing.JEditorPane txtMemberName;
    private javax.swing.JEditorPane txtMemberRollNo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void windowOpened(WindowEvent e) {
    }

    @Override
    public void windowClosing(WindowEvent e) {
        JLabel question = new JLabel("Do you want to quit?");
        JLabel goodbye = new JLabel("Goodbye and see you again!");
        question.setFont(OPTION_PANE_FONT);
        goodbye.setFont(OPTION_PANE_FONT);
        int result = JOptionPane.showConfirmDialog(this,
            question, "Quit Game?",
            JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null,
                    goodbye, "Thanks for playing!",1);
            this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            System.exit(0);
        } else {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }
    }

    @Override
    public void windowClosed(WindowEvent e) {
    }

    @Override
    public void windowIconified(WindowEvent e) {
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
    }

    @Override
    public void windowActivated(WindowEvent e) {
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
    }
}
